# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FixValidationErrors(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TransformationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FixValidationErrors", llm_response=llm_response, mode="request")
        return typing.cast(types.TransformationResult, result)

    def IdentifyRelevantColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="IdentifyRelevantColumns", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[str], result)

    def InferSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InferredSchema:
        result = self.__options.merge_options(baml_options).parse_response(function_name="InferSchema", llm_response=llm_response, mode="request")
        return typing.cast(types.InferredSchema, result)

    def MapColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MappingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MapColumns", llm_response=llm_response, mode="request")
        return typing.cast(types.MappingResult, result)

    def TransformDataGeneral(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TransformationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TransformDataGeneral", llm_response=llm_response, mode="request")
        return typing.cast(types.TransformationResult, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FixValidationErrors(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TransformationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FixValidationErrors", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TransformationResult, result)

    def IdentifyRelevantColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="IdentifyRelevantColumns", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[str], result)

    def InferSchema(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InferredSchema:
        result = self.__options.merge_options(baml_options).parse_response(function_name="InferSchema", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InferredSchema, result)

    def MapColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MappingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="MapColumns", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MappingResult, result)

    def TransformDataGeneral(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TransformationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TransformDataGeneral", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TransformationResult, result)

    