# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class ColumnMapping(BaseModel):
    upload_index: typing.Optional[int] = None
    template_key: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class MappingResult(BaseModel):
    mappings: typing.List["ColumnMapping"]

class RowData(BaseModel):
    row_index: typing.Optional[int] = None
    data: typing.Dict[str, str]

class TemplateColumn(BaseModel):
    key: typing.Optional[str] = None
    name: typing.Optional[str] = None
    required: typing.Optional[bool] = None

class Transformation(BaseModel):
    row_index: typing.Optional[int] = None
    column: typing.Optional[str] = None
    old_value: typing.Optional[str] = None
    new_value: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class TransformationResult(BaseModel):
    transformations: typing.List["Transformation"]

class UploadColumn(BaseModel):
    index: typing.Optional[int] = None
    name: typing.Optional[str] = None
    sample: typing.Optional[str] = None

class ValidationError(BaseModel):
    row_index: typing.Optional[int] = None
    column_key: typing.Optional[str] = None
    value: typing.Optional[str] = None
    error_message: typing.Optional[str] = None

class ValidationRule(BaseModel):
    error_type: typing.Optional[str] = None
    type: typing.Optional[str] = None
    rule: typing.Optional[str] = None
    pattern: typing.Optional[str] = None
    regex: typing.Optional[str] = None
    regex_description: typing.Optional[str] = None
    valid_examples: typing.List[str]
    invalid_examples: typing.List[str]
    common_fixes: typing.Dict[str, str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
