# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.RowData": types.RowData,
    "stream_types.RowData": stream_types.RowData,

    "types.Transformation": types.Transformation,
    "stream_types.Transformation": stream_types.Transformation,

    "types.TransformationResult": types.TransformationResult,
    "stream_types.TransformationResult": stream_types.TransformationResult,

    "types.ValidationError": types.ValidationError,
    "stream_types.ValidationError": stream_types.ValidationError,

    "types.ValidationRule": types.ValidationRule,
    "stream_types.ValidationRule": stream_types.ValidationRule,


}