// admin/src/components/SchemaPreview.tsx
"use client";

import { useState } from "react";
import { ChevronDown, ChevronRight, FileSpreadsheet, Plug, Cog } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";

export interface ColumnInfo {
  column_name: string;
  data_type: string;
  is_nullable: boolean;
}

export interface SchemaPreviewProps {
  fromCsvColumns: ColumnInfo[];
  fromAppColumns: ColumnInfo[];
  autoGeneratedColumns: ColumnInfo[];
  isImported?: boolean;
}

export function SchemaPreview({
  fromCsvColumns,
  fromAppColumns,
  autoGeneratedColumns,
  isImported = false,
}: SchemaPreviewProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [showDeveloperHints, setShowDeveloperHints] = useState(false);

  const totalColumns = fromCsvColumns.length + fromAppColumns.length + autoGeneratedColumns.length;

  if (totalColumns === 0) {
    return null;
  }

  return (
    <div className="rounded-lg border bg-white">
      {/* Level 0: Summary */}
      <div className="p-4">
        <div className="flex items-center gap-2 mb-3">
          {isImported ? (
            <span className="text-green-600 font-medium">✓ Schema imported</span>
          ) : (
            <span className="font-medium text-zinc-900">Ready to import schema</span>
          )}
        </div>

        <ul className="space-y-1 text-sm text-zinc-600">
          <li className="flex items-center gap-2">
            <FileSpreadsheet className="w-4 h-4 text-blue-500" />
            <span>{fromCsvColumns.length} column{fromCsvColumns.length !== 1 ? 's' : ''} from CSV</span>
          </li>
          <li className="flex items-center gap-2">
            <Plug className="w-4 h-4 text-purple-500" />
            <span>{fromAppColumns.length} column{fromAppColumns.length !== 1 ? 's' : ''} from your app</span>
          </li>
          <li className="flex items-center gap-2">
            <Cog className="w-4 h-4 text-zinc-400" />
            <span>{autoGeneratedColumns.length} auto-generated</span>
          </li>
        </ul>

        {/* Level 1: Expand trigger */}
        <Collapsible open={isExpanded} onOpenChange={setIsExpanded}>
          <CollapsibleTrigger className="flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-700 mt-3">
            {isExpanded ? (
              <ChevronDown className="w-4 h-4" />
            ) : (
              <ChevronRight className="w-4 h-4" />
            )}
            <span>Preview columns</span>
          </CollapsibleTrigger>

          <CollapsibleContent className="mt-4">
            {/* Column Lists */}
            <div className="grid grid-cols-3 gap-4 text-sm">
              {/* From CSV */}
              <div>
                <div className="font-medium text-zinc-700 mb-2 flex items-center gap-1">
                  <FileSpreadsheet className="w-4 h-4 text-blue-500" />
                  From CSV
                </div>
                <ul className="space-y-1">
                  {fromCsvColumns.map((col) => (
                    <li key={col.column_name} className="text-zinc-600 font-mono text-xs">
                      {col.column_name}
                    </li>
                  ))}
                  {fromCsvColumns.length === 0 && (
                    <li className="text-zinc-400 italic">None</li>
                  )}
                </ul>
              </div>

              {/* From your app */}
              <div>
                <div className="font-medium text-zinc-700 mb-2 flex items-center gap-1">
                  <Plug className="w-4 h-4 text-purple-500" />
                  From your app
                </div>
                <ul className="space-y-1">
                  {fromAppColumns.map((col) => (
                    <li key={col.column_name} className="text-zinc-600 font-mono text-xs">
                      {col.column_name}
                      {!col.is_nullable && (
                        <Badge variant="outline" className="ml-1 text-[10px] px-1 py-0">
                          required
                        </Badge>
                      )}
                    </li>
                  ))}
                  {fromAppColumns.length === 0 && (
                    <li className="text-zinc-400 italic">None</li>
                  )}
                </ul>

                {/* Level 2: Developer hints */}
                {fromAppColumns.length > 0 && (
                  <Collapsible open={showDeveloperHints} onOpenChange={setShowDeveloperHints}>
                    <CollapsibleTrigger className="flex items-center gap-1 text-xs text-purple-600 hover:text-purple-800 mt-2">
                      {showDeveloperHints ? (
                        <ChevronDown className="w-3 h-3" />
                      ) : (
                        <ChevronRight className="w-3 h-3" />
                      )}
                      <span>How to pass this</span>
                    </CollapsibleTrigger>

                    <CollapsibleContent className="mt-2">
                      <div className="bg-zinc-900 text-zinc-100 p-3 rounded text-xs font-mono overflow-x-auto">
                        <pre>{`<CSVImporter
  context={{
${fromAppColumns.map((col) => `    ${col.column_name}: "..."`).join(",\n")}
  }}
/>`}</pre>
                      </div>
                    </CollapsibleContent>
                  </Collapsible>
                )}
              </div>

              {/* Auto-generated */}
              <div>
                <div className="font-medium text-zinc-700 mb-2 flex items-center gap-1">
                  <Cog className="w-4 h-4 text-zinc-400" />
                  Auto-generated
                </div>
                <ul className="space-y-1">
                  {autoGeneratedColumns.map((col) => (
                    <li key={col.column_name} className="text-zinc-400 font-mono text-xs">
                      {col.column_name}
                    </li>
                  ))}
                  {autoGeneratedColumns.length === 0 && (
                    <li className="text-zinc-400 italic">None</li>
                  )}
                </ul>
              </div>
            </div>
          </CollapsibleContent>
        </Collapsible>
      </div>
    </div>
  );
}
