"""add_webhook_data_fields

Revision ID: 98f92bc3f715
Revises: 34203d60870b
Create Date: 2025-04-24 15:13:23.547319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f92bc3f715'
down_revision: Union[str, None] = '34203d60870b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('importers', sa.Column('include_data_in_webhook', sa.Boolean(), nullable=True))
    op.add_column('importers', sa.Column('webhook_data_sample_size', sa.Integer(), nullable=True))
    op.alter_column('importers', 'webhook_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('importers', 'webhook_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('importers', 'webhook_data_sample_size')
    op.drop_column('importers', 'include_data_in_webhook')
    # ### end Alembic commands ###
