"""Add processed_data and error_message to ImportJob

Revision ID: c55fae69d6b4
Revises: 89df5b3586fc
Create Date: 2025-04-17 10:48:59.799590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55fae69d6b4'
down_revision: Union[str, None] = '89df5b3586fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('processed_data', sa.JSON(), nullable=True))
    op.add_column('import_jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'error_message')
    op.drop_column('import_jobs', 'processed_data')
    # ### end Alembic commands ###
