"""Add key to importer

Revision ID: c734150f184e
Revises: add_token_blacklist
Create Date: 2025-04-26 13:51:24.378207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c734150f184e'
down_revision: Union[str, None] = 'add_token_blacklist'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_token_id', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('importers', sa.Column('key', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_importers_key'), 'importers', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_importers_key'), table_name='importers')
    op.drop_column('importers', 'key')
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_blacklist_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token_id', 'token_blacklist', ['token_id'], unique=True)
    # ### end Alembic commands ###
