"""add_webhook_deliveries_table

Revision ID: f672aa83af9a
Revises: d284a29c464c
Create Date: 2026-01-18 21:29:36.054120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f672aa83af9a'
down_revision: Union[str, None] = 'd284a29c464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('request_url', sa.String(length=2048), nullable=False),
    sa.Column('request_payload_preview', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body_preview', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Enum('SUCCESS', 'FAILED', 'RETRY_SUCCESS', name='webhookdeliverystatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['importer_destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_destination_id'), 'webhook_deliveries', ['destination_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_destination_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.execute('DROP TYPE IF EXISTS webhookdeliverystatus')
    # ### end Alembic commands ###
