name: Frontend Tests

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  unit-tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Run Vitest tests
        run: npm test -- --reporter=verbose

      - name: Generate coverage report
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./frontend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-check:
    name: Build Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build React mode
        run: npm run build:react

      - name: Build Preact mode
        run: npm run build:preact

      - name: Build Bundled mode
        run: npm run build:bundled

      - name: Check build artifacts
        run: |
          test -f build/react/index.js || exit 1
          test -f build/preact/index.esm.js || exit 1
          test -f build/bundled/index.umd.js || exit 1

  all-tests-complete:
    name: All Tests Passed
    needs: [unit-tests, build-check]
    runs-on: ubuntu-latest
    steps:
      - name: All tests completed successfully
        run: echo "✅ All frontend tests passed"
